server:
  port: 8080

spring:
  application:
    name: E-Commerce API
  datasource:
    url: jdbc:mysql://mysql:3306/accounts_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# JWT Configuration
jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong
  expiration: 86400000

# Stripe Configuration (for payment integration)
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY:sk_test_dummy_key_for_development}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY:pk_test_dummy_key_for_development}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_dummy_secret_for_development}

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging Configuration
logging:
  level:
    com.JDMGod.accounts_service: INFO
    org.springframework.security: INFO
